name: prerelease
on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
          token: ${{secrets.GITHUB_TOKEN}}
          prerelease: 'true'
          default-branch: development