name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: master
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
        if: ${{ steps.release.outputs.release_created }}
      - name: Auto merge
        run: |
          git checkout development
          git pull
          git merge --no-ff master -m "chore: auto-merge to development"
          git push
        if: ${{ steps.release.outputs.release_created }}