on: push

name: release-please-submodule
jobs:

  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      simplePaths: ${{ steps.interrogate.outputs.simplePaths }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - id: interrogate
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
            });
            const { execSync } = require("child_process");
            const changedPaths = execSync(`git diff --name-only origin/master ${latestRelease.data.tag_name}`, {
              encoding: "utf-8",
            }).split('\n');
            
            console.log(`\n$!!! {changedPaths.length} changes from latest release: ${latestRelease.data.tag_name} !!!\n\n`);
            
            const fs = require('fs');
            const splitPaths = require("./scripts/split-paths.js");
            const apps = splitPaths({ changedPaths, fs, forRelativePath: 'ui/apps' });
            console.log(`::set-output name=simplePaths::${JSON.stringify(apps.simplePaths)}`);

#  release:
#    runs-on: ubuntu-latest
#    needs: changeFinder
#    strategy:
#      fail-fast: false
#      matrix:
#        package: ${{fromJson(needs.changeFinder.outputs.simplePaths)}}
#    steps:
#      - uses: google-github-actions/release-please-action@v3
#        id: tag-release
#        with:
#          path: ui/apps/${{ matrix.package }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          release-type: simple
#          monorepo-tags: true
#          package-name: ${{ matrix.package }}
#          command: github-release
#          bump-minor-pre-major: true
#          bump-patch-for-minor-pre-major: true
#
#
#  release-pr:
#    runs-on: ubuntu-latest
#    needs:
#      - changeFinder
#      - release
#    strategy:
#      fail-fast: false
#      matrix:
#        package: ${{fromJson(needs.changeFinder.outputs.simplePaths)}}
#    steps:
#      - uses: google-github-actions/release-please-action@v3
#        id: release-please
#        with:
#          path: ui/apps/${{ matrix.package }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          release-type: simple
#          package-name: ${{ matrix.package }}
#          monorepo-tags: true
#          command: release-pr
#          bump-minor-pre-major: true
#          bump-patch-for-minor-pre-major: true